main: me.vilmu.waterwars.WaterWars
version: 0.0.1
name: WaterWars
author: vilmu
description: A water wars arena game plugin
api-version: 1.13

commands:
 ww:
  description: Use WaterWars commands
  permission: waterwars.commands.command
  aliases: waterwars
   
permissions:   
 waterwars.*:
  children:
   - waterwars.commands.*
  
 waterwars.commands.*:
  children:
   - waterwars.commands.admin
   - waterwars.commands.player
   
   
   
     