main: me.vilmu.waterwars.WaterWars
version: 0.0.1
name: WaterWars
author: vilmu
description: A water wars arena game plugin
api-version: 1.13

commands:
 ww:
  description: Use WaterWars commands
  aliases: waterwars
 pg:
  description: Use WaterWars private game commands
  aliases: privategame
   
permissions:   
 waterwars.*:
  children:
   - waterwars.commands.*:
      children:
       - waterwars.commands.admin: op
       - waterwars.commands.player: true
       - waterwars.commands.privategame.*:
          children:
           - waterwars.commands.privategame.host: op
           - waterwars.commands.privategame.join: true
   
   
     